### PR TITLE
Quick cleanup and new way of sending messages

### PR DESCRIPTION
**Pull request by NathanPERIER**
Hello ! I just installed Ntfy on my server and I noticed you had made this nice library. There were a few changes I wanted to make for using it myself, so here they are in case you are interested. Feel free to pick some things if you don't want everything. If you want, I can always make a new branch with only the changes you like.

First of all, I noticed you had quite a bit of code duplication between `raw_send`, `raw_subscribe` and the `NTFYClient`. By simply calling `raw_send` and `raw_subscribe` in the methods of `NTFYClient`, you can reduce the size of the class by a lot, which is always nice. I also slightly modified the signature of `raw_subscribe` and `NTFYClient.subscribe` to accept an optional parameter, which is a function that is applied on all the messages. By default it is `print`, so any existing code won't be affected, but you can also pass another function and do whatever you want with the messages.

A also added type hints in some places, it helps me spot errors sometimes so I like to do it, and I splitted the classes in different files because it can help preventing import errors sometimes.

The main chunk of code I wrote is related to a new `NTFYPushMessage`, which is a data structure that contains the arguments for `NTFYClient.send`. It allows the users to build the message by adding the properties one by one, which is convenient when you use a lot of optional fields (you would have a super long line of code otherwise). I also added data structures to help make the header for the actions, because the syntax for those is quite annoying, and I also started doing the same for the attachments but I could not implement those completely because it might require some breaking changes. I added a few examples to illustrate how it works in `/examples`.

Overall, I think there are a lot of ways user input could break this implementation. For example, if the user needs to put a `;` in a action's field, that would probably break the actions. This is why I think it may be better to use [the JSON format](https://docs.ntfy.sh/publish/#publish-as-json) instead of headers to transmit the options.

### CODE REVIEW

**Comment by Nevalicjus** [comment]
Hi!
I am very happy the little library I've created in a hurry was useful to you!:)
I have looked through your changes, and I haven't found ones I'd really remove, so they're all coming 😅 

I have made some little corrections, like single quotes to double in examples to fit the rest of the code, or name "consumer" to "func" in the `raw_subscribe` function (it sounded better for me) (a very good addition btw!).

As I'm not a heavy user of actions, I haven't thought of strong JSONyfing of the requests' data, but I agree this would be a good change, so I've changed the raw_send to put the options in data instead of headers, which is then properly dumped as json (I had to remove code in client.py that formatted actions and tags for the non-JSON format, but I'm not sure if anything else in other actions code is in need of fixing).

If I catch a breath of free time I'll look into actions (double checking I haven't broken anything) and attachments (same treatment as actions) myself, but if you'd beat me to it go ahead, I'll keep this pr open until one of us does:)

Also, thanks for creating examples!

**Comment by NathanPERIER** [comment]
I had a quick look at the new code for `raw_send`, and I think there might be an issue there. You see, arguments like `tags` and `actions` were previously passed as strings, but now they need to be in JSON form. We could change the contract of the method to accept the correct data structures, but this will break existing code. If you consider that to be a problem, we can also leave `raw_send` as it was before, and create a `raw_send_message` method to deal with `NTFYPushMessage`s directly.

**Comment by NathanPERIER** [comment]
After closer inspection, I think I see what you did : you changed the types of the arguments in `raw_send` to correspond to the contents of `NTFYPushMessage`. You should also update the type hints in `NTFYClient.send` and `raw_send` to correspond to the new types then. Type checking in Python can actually be very convenient to avoid making some errors, so we must make sure that the types hints are correct. I don't know what IDE you are using, but in VS Code you can enable type checking by adding a `.vscode/settings.json`file with the following content :
```json
{
	"python.analysis.typeCheckingMode": "basic"
}
```

**Comment by NathanPERIER** [comment]
So basically : 
- I added methods to allow converting the `NTFYPushMessage`, the actions and the attachment to JSON ([b44be30](https://github.com/Nevalicjus/ntfpy/pull/1/commits/b44be30bc9d561fb5d13edcb8e4f562d07592f3a))
- I then added a `send_raw_message` method that uses this formatted data to make a request, and I made `send_raw` use this method via a `NTFYPushMessage` created internally ([656b411](https://github.com/Nevalicjus/ntfpy/pull/1/commits/656b4110a3ae054f5709183ec6dab9946ea8b025))

I think it should help reducing code duplication as much as possible, while keeping methods with roughly the same signature as before, let me know what you think. I also checked that it is still working with the existing examples.

**Comment by Nevalicjus** [comment]
Thanks again for more fixes I should've done myself 😅

I have made some again small changes, like adding and removing whitespace, or order of imports, remove(tag/action) functions for `NTFYPushMessage`.

Also, what do you think of merging `NTFYMessage` and `NTFYPushMessage`? - with assigning id & timestamp as `None` (on to-be-sent, but to regular values on received) as a drawback.

P.S. Thanks for the IDE tips, but I actually rarely use IDEs, more often 'regular' text editors.

**Comment by NathanPERIER** [comment]
I've thought about merging the messages, but I am not sure how I feel about having some unused fields... I generally avoid doing that because I think it may lead to some misunderstandings for the devs using the object. This would also mean that we would have setters for received objects, which I find kind of weird as well (ideally, these would be read-only objects).

I think it may even be quite good to keep the messages for sending and receiving separated, because it will reduce the risk of mixing them together (which we don't usually want).

**Comment by Nevalicjus** [comment]
Got you.
I'll think about it more but it's definitely not happening now.

If there's nothing else to discuss I'll be merging this, thus bumping to 0.0.9

**Review by Nevalicjus — APPROVED** [review]

**Pull request merged**
